<?php

function favorites_menu() {
  $an_array = array(
    'movies' => array('The Princess Bride', 'Boogie Nights', 'Dangerous Liaisons'),
    'books' => array('A Farewell To Arms', 'The Star is My Destination', 'Cloud Atlas'),
    'songs' => array('Go West', 'West End Girls', 'Anything by Kanye'),
  );

foreach ($an_array as $things => $values) {
  $subarray = array($things, $values);
  $items['favorites/'.$things] = array(
    'title' => 'My favorite '.$things,
    'page callback' => 'my_favorites',
    'page arguments' => array($subarray),
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
    );
  }
  return $items;
}

// $favorites = 'justice';

function my_favorites($input) {
  $output = '';
  $what_it_is = $input[0];
  foreach ($input[1] as $key => $value) {
    $output.= '<li>'.$value.'</li>';
  }
  return "<p>Here's some". $what_it_is. " I really like!</p><ul>".$output.'</ul>';
}
