<?php

  function pets_menu() {
    $items = array();
    $items['pet_pics'] = array(
      'title' => 'pet pics',
      'page callback' => 'pet_pics',
      'access callback' => TRUE,
      'type' => MENU_NORMAL_ITEM,
    );
    return $items;
  }
  
  // drupal_get_path('module', 'pets') used to get path for IMG

  function pet_pics() {
    return
      '<p>Hey, check out this crazy guy!</p>
      <img src="/sites/all/modules/pets/kalgar.jpg" alt="Kalgar the puddle-drinker"><br>
      <a href="https://en.wikipedia.org/wiki/Labrador_Retriever">Click here for more information about yellow labs!</a>';

  }
