<?php

function greetings_menu() {
    $items['greetings'] = array(
       'title' => 'Hello!',
       'page callback' => 'say_hello',
       'access callback' => TRUE,
       'type' => MENU_CALLBACK,
    );
    $items['goodbyes'] = array(
       'title' => 'Goodbye!',
       'page callback' => 'say_goodbye',
       'access callback' => TRUE,
       'type' => MENU_CALLBACK,
    );
    return $items;
}

function say_hello() {
    return '<p>How is things going Pie Guy!</p>';
}

function say_goodbye() {
    return '<p>Take it easy buddy!</p>';
}

function greetings_user_login() {
    $_GET['destination'] = 'greetings';
}

function greetings_user_logout() {
    $_GET['destination'] = 'goodbyes';
}
